# Generated by Django 5.0.6 on 2024-05-26 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_listed_user_chatroom_fellow_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message1', to='chat.chatroom'),
        ),
        migrations.AddField(
            model_name='message',
            name='room2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message2', to='chat.chatroom'),
        ),
    ]
