# Generated by Django 5.0.6 on 2024-05-08 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
    ]
