# Generated by Django 5.0.6 on 2024-05-14 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_rename_area_string_area_area_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='area', to='services.area')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='area', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
