# Generated by Django 5.0.6 on 2024-05-14 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_userarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userarea',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='services.area'),
        ),
    ]
