# Generated by Django 5.0.6 on 2024-05-14 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_userarea_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceareas',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.area'),
        ),
    ]
