# Generated by Django 5.0.6 on 2024-05-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_serviceareas_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(max_length=100),
        ),
    ]
