# Generated by Django 5.0.6 on 2024-05-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_service_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='is_hidden',
            field=models.BooleanField(default=True),
        ),
    ]
