# Generated by Django 5.0.6 on 2024-06-02 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_area_permit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetype',
            options={'ordering': ['service_name']},
        ),
    ]
