# Generated by Django 5.0.6 on 2024-06-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_service_knock_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='knock_count',
            field=models.IntegerField(default=0),
        ),
    ]
