# Generated by Django 5.0.6 on 2024-06-04 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myusers_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnockedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knockee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knocks', to=settings.AUTH_USER_MODEL)),
                ('knocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knocked_at', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
