# Generated by Django 5.0.6 on 2024-06-04 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_knockedusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KnockedUsers',
        ),
    ]
