# Generated by Django 5.0.6 on 2024-06-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
